local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {desc = 'Files' })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {desc = 'Grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, {desc = 'Buffers' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {desc = 'Help' })
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader><space>', require('telescope.builtin').buffers, { desc = '[ ] Find existing buffers' })
