return {
    -- {
    --     'saghen/blink.cmp',
    --     dependencies = 'rafamadriz/friendly-snippets',
    --     -- use a release tag to download pre-built binaries
    --     version = 'v0.*',
    --     opts = {
    --         appearance = {
    --             use_nvim_cmp_as_default = true,
    --             nerd_font_variant = 'mono'
    --         },
    --         sources = {
    --             default = { 'lsp', 'path', 'snippets', 'buffer' },
    --             -- optionally disable cmdline completions
    --             -- cmdline = {},
    --         },
    --
    --         -- experimental signature help support
    --         signature = { enabled = true }
    --     },
    --     opts_extend = { "sources.default" },
    --     completion = {
    --         menu = {
    --             draw = {
    --                 columns = { { "label", "label_description", gap = 1 }, { "kind_icon", "kind" } },
    --             },
    --         },
    --     }
    -- },
}
